### PR TITLE
Update CMake to set warning level 4 by default

### PR DESCRIPTION
**Pull request by greenozon**

### CODE REVIEW

**Comment by Luca1991** [comment]
Thank you @greenozon 
As I said in the issue (I edited the message, so maybe you missed it), I would remove the /WX flag (in order to avoid build failures running the gh release action).
Can you edit it? Or if you prefer, I'll edit it later tonight!
Thanks

**Comment by Luca1991** [comment]
Ah just as a side note, please use different branches for different PRs otherwise your commits history will get polluted ;)

**Comment by Luca1991** [comment]
> should I create a new branch each time, create PR to here and then remove it as a temp stuff and return back to main, sync it with yours and then again?

100% correct! This is the way to go :)
You should keep the main/master branch of your fork clean, up-to-date and in sync with the one of this repo. Everytime you want to contribute a PR, you should create a new branch from your main/master, write your code and then send a PR from your branch to the main of this repository (after the merge, you can delete it if you want). 
This has many advantage, plus you can work on multiple tasks and send multiple PRs at the same time by just switching form a branch to another :)

**Comment by greenozon** [comment]
OK! thanks for great points
but how should I clean now my master branch... should I revert to some point in the past?

**Comment by Luca1991** [comment]
You can do a `git revert --hard` to an older commit, force push and then you can directly sync from your fork page on GitHub (another approach, widely used in the past, is to add an upstream to your git remotes, but since GH now supports syncing from the web, there is no needs anymore).

**Comment by Luca1991** [comment]
Hi @greenozon 
can you remove the /WX flag so I can merge this PR?
Thanks

**Comment by greenozon** [comment]
yeah, sorry for delay
and thanks for hints!

**Comment by Luca1991** [comment]
No problem and thanks a lot :)

**Pull request merged**
